#/**********
# * Makefile
# *********/
#/******************************************************************************
# * Aluno: André Meneghelli Vale,      Núm. USP: 4898948
# * Curso: Bacharelado em Ciências da Computação
# * Tarefa 7 -- Calculo do diâmetro de um grafo.
# * MAC0328 -- 17/04/2013 -- IME/USP, -- Prof. Paulo Feofiloff
# * Compilador: gcc linux 4.6.3
# * Editor: Sublime Text 2;
# * Sistema Operacional: Linux
# *****************************************************************************/

CC=gcc
OPTS = -Wall -D _BSD_SOURCE -pedantic -ansi -O2 -U_FORTFY_SOURCE -g

t7: tarefa7.c
	$(CC) $(OPTS) tarefa7.c -o $@
clean:
	rm t7
	rm *.o