#!/usr/bin/perl

# RODAR ulimit -s 1024

$n_args = $#ARGV + 1;

if ($n_args < 2) {
	print "Entrada incorreta!\n";
	exit 0;
}
else {
	$m = $ARGV[0]; chomp $m;
	$n = $ARGV[1]; chomp $n;
	for($i = 2; $i < $n_args; $i++) {
		if ($ARGV[$i] eq "c") {
			$c = 1;
		}
		if ($ARGV[$i] eq "s") {
			$s = 1;
		}
	}	
}

if ($c) {
	system "rm -f ep1";
	system "make";
}
if ($s) {
	system "./ep1 $m $n caca";
}
else {
	system "./ep1 $m $n";
}
